# Generated by Django 4.0.3 on 2022-04-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.SlugField(unique=True, verbose_name='brand ID')),
                ('brand_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='brand code')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.SlugField(unique=True, verbose_name='category ID')),
                ('code', models.CharField(blank=True, max_length=70, null=True, verbose_name='category code')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.SlugField(unique=True, verbose_name='product_id')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('selling_price', models.BigIntegerField(blank=True, null=True, verbose_name='price')),
                ('discounted_price', models.BigIntegerField(blank=True, null=True, verbose_name='discounted price')),
                ('discount_percent', models.IntegerField(blank=True, null=True, verbose_name='discount percent')),
                ('rating_value', models.IntegerField(blank=True, null=True, verbose_name='rate from 100')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.SlugField(unique=True, verbose_name='seller ID')),
                ('seller_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='seller code')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_id', models.SlugField(unique=True, verbose_name='subcategory ID')),
                ('code', models.CharField(blank=True, max_length=70, null=True, verbose_name='subcategory code')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='vendor name')),
                ('url', models.URLField(verbose_name='vendor url')),
            ],
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='supermarket_name_a46fe9_idx'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='supermarket_api.category'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['seller_id'], name='supermarket_seller__cc7cf3_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supermarket_api.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supermarket_api.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supermarket_api.seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supermarket_api.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supermarket_api.vendor'),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supermarket_api.product'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['cat_id'], name='supermarket_cat_id_c64ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_id'], name='supermarket_brand_i_926fee_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['sub_cat_id'], name='supermarket_sub_cat_ca3c43_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_id'], name='supermarket_product_c1a5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='supermarket_categor_59585a_idx'),
        ),
    ]
