# Generated by Django 4.0.3 on 2022-04-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.BigIntegerField(blank=True, null=True, verbose_name='price')),
                ('discounted_price', models.BigIntegerField(blank=True, null=True, verbose_name='discounted price')),
                ('discount_percent', models.IntegerField(blank=True, null=True, verbose_name='discount percent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket_api.product', to_field='product_id')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket_api.seller', to_field='seller_id')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='selling_info',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', through='supermarket_api.ProductPriceSeller', to='supermarket_api.seller'),
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supermarket_api.product', to_field='product_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supermarket_api.brand', to_field='brand_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supermarket_api.category', to_field='cat_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supermarket_api.subcategory', to_field='sub_cat_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supermarket_api.vendor', to_field='name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='supermarket_api.category', to_field='cat_id'),
        ),
        migrations.AddIndex(
            model_name='productpriceseller',
            index=models.Index(fields=['product', 'seller'], name='supermarket_product_5da556_idx'),
        ),
    ]
