# Generated by Django 4.0.3 on 2022-04-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0003_alter_product_selling_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_code',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default='میهن', max_length=500, unique=True, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount percent'),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='discounted price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('M', 'merketable'), ('U', 'unmarketable')], max_length=1, null=True, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='ProductPriceSeller',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
