# Generated by Django 4.0.3 on 2022-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0005_mainimage_otherimages_delete_images_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='supermarket_brand_i_926fee_idx',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_id',
            new_name='brand_code',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('merketable', 'merketable'), ('unmarketable', 'unmarketable')], max_length=12, null=True, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_code'], name='supermarket_brand_c_f5820c_idx'),
        ),
    ]
