# Generated by Django 4.0.3 on 2022-04-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0006_remove_brand_supermarket_brand_i_926fee_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_code',
            field=models.SlugField(unique=True, verbose_name='brand code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='supermarket_api.mainimage', to_field='url'),
        ),
    ]
