# Generated by Django 4.0.3 on 2022-04-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0007_alter_brand_brand_code_alter_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AddField(
            model_name='mainimage',
            name='product',
            field=models.OneToOneField(default='fgffg', on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='supermarket_api.product', to_field='product_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
    ]
