# Generated by Django 4.0.3 on 2022-04-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='title'),
        ),
    ]
