# Generated by Django 4.0.3 on 2022-04-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0011_alter_brand_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='title'),
        ),
    ]
