# Generated by Django 4.0.3 on 2022-04-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0013_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_code',
            field=models.TextField(unique=True, verbose_name='brand code'),
        ),
    ]
