# Generated by Django 4.0.3 on 2022-04-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0014_alter_brand_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='title'),
        ),
    ]
