# Generated by Django 4.0.3 on 2022-04-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0015_alter_product_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='supermarket_categor_59585a_idx',
        ),
    ]
