# Generated by Django 4.0.3 on 2022-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0017_alter_product_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='supermarket_brand_c_f5820c_idx',
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='brand name'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_name'], name='supermarket_brand_n_8711fb_idx'),
        ),
    ]
